% Get the 5% and 95% boundary for MCtest
function [lb, rb,lb_alpha, ub_alpha, lb_beta, ub_beta] ...
    = GetBounds(DJF, MAM, JJA, SON, oMON, rm, alpha, beta)
lb_alpha = zeros(10, 14, 4);
ub_alpha = zeros(10, 14, 4);
lb_beta  = zeros(10, 14, 4);
ub_beta  = zeros(10, 14, 4);

[lb_DJF, rb_DJF, ...
 lb_alpha(:,:,1), ub_alpha(:,:,1), lb_beta(:,:,1), ub_beta(:,:,1)] ...
            = MCtestSeason(DJF, oMON(:,:,:,1), ...
            int8(squeeze(rm(:,:,1).*3520)), alpha(:,:,1), beta(:,:,1));
[lb_MAM, rb_MAM,...
lb_alpha(:,:,2), ub_alpha(:,:,2), lb_beta(:,:,2), ub_beta(:,:,2)] ...
            = MCtestSeason(MAM, oMON(:,:,:,2), ...
            int8(squeeze(rm(:,:,2).*3588)), alpha(:,:,2), beta(:,:,2));
[lb_JJA, rb_JJA,...
lb_alpha(:,:,3), ub_alpha(:,:,3), lb_beta(:,:,3), ub_beta(:,:,3)] ...
            = MCtestSeason(JJA, oMON(:,:,:,3), ...
            int8(squeeze(rm(:,:,3).*3588)), alpha(:,:,3), beta(:,:,3));
[lb_SON, rb_SON,...
lb_alpha(:,:,4), ub_alpha(:,:,4), lb_beta(:,:,4), ub_beta(:,:,4)] ...
            = MCtestSeason(SON, oMON(:,:,:,4), ...
            int8(squeeze(rm(:,:,4).*3549)), alpha(:,:,4), beta(:,:,4));

lb = zeros(10,14,4,4); rb = zeros(10,14,4);
lb(:,:,:,1)=lb_DJF; lb(:,:,:,2)=lb_MAM; lb(:,:,:,3)=lb_JJA; lb(:,:,:,4)=lb_SON;
rb(:,:,:,1)=rb_DJF; rb(:,:,:,2)=rb_MAM; rb(:,:,:,3)=rb_JJA; rb(:,:,:,4)=rb_SON;

clear lb_DJF lb_MAM lb_JJA lb_SON rb_DJF rb_MAM rb_JJA rb_SON
